### ISSUE TITLE
can you add a upload file operation: convey the file binary content

### ISSUE THREAD

**Issue by adamydwang** [ufilesdk-dev/ufile-gosdk#10]

**Comment by adamydwang** [comment]
we often use sdk to pull image to ufile. and the image we extract from video and the image has been loaded in memory such as a []byte.  so can u add a new operation, which will be more convinient

**Comment by leyafo** [comment]
OK, I will made a io.Writer interface for put and mput upload. It will done by this weekend.

**Comment by leyafo** [comment]
hi @adamydwang 
I made two io.reader upload interfaces. 
this is the API document. 

mutipart upload:
https://godoc.org/github.com/ufilesdk-dev/ufile-gosdk#UFileRequest.IOMutipartAsyncUpload

put upload:
https://godoc.org/github.com/ufilesdk-dev/ufile-gosdk#UFileRequest.IOPut

Thank you for using UFile.
Have fun for you happy conding.
