### ISSUE TITLE
https Schema Support

### ISSUE THREAD

**Issue by chowyu08** [ufilesdk-dev/ufile-gosdk#16]
Schema only support http [here](http://api.ucloud.cn/?Action=DescribeBucket&BucketName=s488594zqqrz7v3y&Limit=20&Offset=0&ProjectId=org-i2dxye&PublicKey=YQfS658uqbfAshhYWN0H2Fpsy5G%2B3S91f71htAcXDVOOitgNDaqWXZtyyjTi%2FCe9&Signature=02b9e8210729792310b50b7161c912552b4f6e75)

and [here](https://github.com/ufilesdk-dev/ufile-gosdk/blob/master/request.go#L121)

**Comment by kuixiao** [comment]
已在2021的产品规划中，请关注SDK的更新

**Comment by kuixiao** [comment]
Already in the 2021 product plan, please pay attention to the update of the SDK.
