### ISSUE TITLE
文件下载

### ISSUE THREAD

**Issue by clpdyhm** [ufilesdk-dev/ufile-gosdk#2]
在file.go中，只有一个Download函数，该函数只是发起一个http请求，请提供能将baody数据直接存放到文件中的函数，比如：Download(localFileName, fileKey string)

**Comment by leyafo** [comment]
你获取 request 里面的 LastResponseBody 就可以了。这个就是文件内容。

**Comment by clpdyhm** [comment]
嗯嗯，好的。我的意思是，能不能提供一个将文件内容直接保存在本地文件中的接口？还有，这个接口是不是不用 Authorization和Range头部也可以下载成功？

**Comment by leyafo** [comment]
@clpdyhm 这个如果用 go 语言的方式来实现，应该是外部传一个write接口进来，然后我往里面写数据。这个我们还没想好怎么用更好的方式提供出来，想好了会以更易用的方式提供出来。这个接口目前只是包装 http 请求。
需要你这边调用 GetPublicURL 或 GetPrivateURL 接口获取url再下载。
