### ISSUE TITLE
invalid signature

### ISSUE THREAD

**Issue by clpdyhm** [ufilesdk-dev/ufile-gosdk#3]
请问各个接口是否已经测试过，我这里出现以下问题。
调用file.go中接口PrefixFileList出现403错误，具体错误：{ "RetCode": -148658, "ErrMsg": "invalid signature" }。
但是，使用同样的公私钥配置，利用“管理工具filemgr-linux64”可以获取到文件列表。
请看看是不是生成signature的方式有问题。谢谢！

**Comment by leyafo** [comment]
你把配置文件配置好，运行 example/demo_file.go 看看能否成功运行，这里面有所有的接口测试。
另外你把你的接口调用代码贴上来，我看看是不是SDK代码有bug。

**Comment by clpdyhm** [comment]
不好意思，是我的问题。原因是，受v1的影响，将file_host配置为：www.cn-bj.ufileos.com，应该是：cn-bj.ufileos.com。现在功能一切正常。谢谢你的解答。
