### ISSUE TITLE
mput 出错

### ISSUE THREAD

**Issue by wu1boy** [ufilesdk-dev/ufile-gosdk#5]
使用mput 接口时. 报错 Post http://vdplay.ufile.ucloud.com.cn/zmg182x78q.mp4?uploads: EOF

代码 :     err = req.MPut(localFileName, keyName, "")

**Comment by leyafo** [comment]
用 asyncmput 会有问题吗？

**Comment by leyafo** [comment]
@wu1boy 上次我让你做的那个因为很多个 http request 连接复用导致的 EOF错误，把 request 调用 close 后还有问题吗？

**Comment by leyafo** [comment]
和这里是同一个问题，https://github.com/ufilesdk-dev/ufile-gosdk/issues/9
已经修复。
