### ISSUE TITLE
UploadPart导致内存泄漏

### ISSUE THREAD

**Issue by clpdyhm** [ufilesdk-dev/ufile-gosdk#9]
@leyafo 函数UploadPart中，
resp, err := u.requestWithResp(req)
未调用resp.Body.Close()
导致内存泄漏

**Comment by leyafo** [comment]
好的，我改下。

**Comment by leyafo** [comment]
UploadPart 里面并没有去读 body，有具体的出错信息吗？发一下。

**Comment by clpdyhm** [comment]
没有出错信息，只是进程导致内存泄漏后，导致OOM错误，被OS kill掉。即使没有读Body，也是需要Close的，不然，这段内存不会得到释放。

**Comment by leyafo** [comment]
@clpdyhm 我先调用 close fix这个问题，后续我再自己查下 go 的源码，看看具体是怎么回事。

**Comment by leyafo** [comment]
https://github.com/ufilesdk-dev/ufile-gosdk/commit/697866ec6bc54ef43609099fca94b4c7c7f9f62d
已经fix

**Comment by leyafo** [comment]
经过仔细排查，这个内存泄漏确实是没有 close body 导致的。
